inherit_from:
  - .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/migrate/**/*"
    - "db/schema.rb"
    - "config/**/*"
    - "script/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 12

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 32

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 69

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Rails/HasAndBelongsToMany:
  Exclude:
    - "app/models/role.rb" # This instance was auto generated.

Rails/Output:
  Exclude:
    - "db/seeds.rb"
